#!/bin/bash
# Builds and opens my Elm project

# Doing things in serial/parallel
# https://unix.stackexchange.com/questions/63648/how-to-send-many-commands-to-shell-and-wait-for-the-command-behind-ends

# compile my script
elm-make Main.elm --output=main.js --debug &&
# open it
chromium Upload.html
